/**
 * Embedded fallback copy of `src/prompts.json` plus its type.
 *
 * GENERATED by `scripts/sync-prompts.mjs` (run automatically by the
 * `prebuild` and `pretest` npm scripts) — do not hand-edit the strings
 * here; edit `src/prompts.json` instead. The built `lib/` keeps working
 * even when the JSON is absent from a stale install (the embedded defaults
 * are the same strings the package always shipped).
 *
 * @module @ai4rpg/dsh-stage-switch/prompts.defaults
 */

/** All user-facing prompt copy owned by stage-switch (formats excluded). */
export interface StageSwitchPrompts {
  /** Model-facing `goto_stage` tool copy. */
  readonly gotoTool: {
    readonly description: string
    readonly stageParam: string
    readonly handoffParam: string
  }
  /** The transition-review dialog presented through user-questions. */
  readonly review: {
    readonly header: string
    readonly fullQuestion: string
    readonly lightQuestion: string
    readonly approveLabel: string
    readonly keepStageLabel: string
    readonly fullApproveDescription: string
    readonly lightApproveDescription: string
    readonly keepStageDescription: string
  }
  /** The `goto_stage` tool-result render copy. */
  readonly toolResult: {
    readonly approved: string
    readonly handoffPath: string
  }
  /** Tool-call card copy. */
  readonly present: {
    readonly callTitle: string
    readonly lightCallContent: string
    readonly resultTitle: string
  }
  /** Stage-switch notice copy (the `source.summary` formats stay in code). */
  readonly notice: {
    readonly handoffReplaced: string
    readonly userSwitchPrefix: string
  }
  /** Failure messages surfaced to the model. */
  readonly errors: Record<
    'notConfigured' | 'alreadyCurrent' | 'requiresHandoff' | 'noUserQuestions'
    | 'noFs' | 'missingTokenMeter' | 'keepPlanning' | 'keepPlanningFeedback' | 'dismissed',
    string
  >
  /** The `/stage` command copy. */
  readonly command: {
    readonly description: string
    readonly current: string
    readonly unknown: string
    readonly alreadyCurrent: string
    readonly switched: string
    readonly queued: string
  }
}

/** The fallback copy of `src/prompts.json`; regenerated by the sync script. */
export const DEFAULT_STAGE_SWITCH_PROMPTS = {
  "gotoTool": {
    "description": "Use when the current stage is complete and a later stage should take over. Name the target stage; the user approves the transition. A full transition archives the conversation and you continue from the handoff document; a light transition just switches the stage. Write a handoff only when the handoff parameter requires one.",
    "stageParam": "The target stage name; must be in the configured stages list.",
    "handoffParam": "Optional; omit it. A light transition never uses a handoff document. A full transition rejects a call without one and shows the handoff template in the rejection — retry with the handoff following that template."
  },
  "review": {
    "header": "Stage transition",
    "fullQuestion": "Approve switching to stage \"{stage}\" and archiving the conversation?",
    "lightQuestion": "Approve switching to stage \"{stage}\"?",
    "approveLabel": "Approve",
    "keepStageLabel": "Keep current stage",
    "fullApproveDescription": "Switch stages; the conversation is archived and the handoff document takes over.",
    "lightApproveDescription": "Switch to the next stage; the conversation stays as it is.",
    "keepStageDescription": "Stay in the current stage; feedback goes back to the model."
  },
  "toolResult": {
    "approved": "Stage transition to \"{stage}\" approved — the stage takes effect from the next step.",
    "handoffPath": " Read the handoff document at {path}."
  },
  "present": {
    "callTitle": "Stage transition: {stage}",
    "lightCallContent": "Switch to stage {stage} (small conversation, no handoff document).",
    "resultTitle": "Stage transition"
  },
  "notice": {
    "handoffReplaced": "Stage switched to {stage}. The previous conversation was archived. Read the handoff document at {path} before continuing.",
    "userSwitchPrefix": "The user switched this session to stage {stage}. "
  },
  "errors": {
    "notConfigured": "goto_stage target stage \"{stage}\" is not in the configured stages ({stages})",
    "alreadyCurrent": "goto_stage target stage \"{stage}\" is already the current stage",
    "requiresHandoff": "This conversation is large enough to require a full transition, which archives the conversation and continues from a handoff document. Call goto_stage again with a `handoff` markdown that lets the target stage resume with no loss of essential context, using exactly this structure — every section in order, terse bullets, \"(none)\" for an empty section:\n\n## Primary Request and Intent\n- [the user's original and evolving goals; quote verbatim where the exact wording matters]\n\n## Key Technical Concepts\n- [technologies, frameworks, patterns, and conventions in play]\n\n## Files and Code\n- [exact path: why it matters, key changes or snippets]\n\n## Errors and Fixes\n- [error: how it was resolved, plus any related user feedback]\n\n## Pending Jobs\n- [explicitly requested work not yet completed]\n\n## Current Work\n- [precisely what was in progress at this switch]\n\n## Next Step\n- [the single next action for the target stage, or \"(none)\"]\n\n## Critical Context\n- [decisions and their rationale, constraints, user preferences, open questions, data needed to continue]\n\nRules: concise engineering prose; preserve exact file paths, commands, error strings, identifiers, numeric values, and function signatures; capture user feedback and corrections faithfully. Include only what the target stage needs; do not restate the whole conversation, do not duplicate content already recorded in documents.",
    "noUserQuestions": "no user-questions channel is available to review the stage transition; ask the user to switch the stage manually",
    "noFs": "no filesystem service is available to write the handoff document; mount a filesystem backend or ask the user to switch the stage manually",
    "missingTokenMeter": "StageConfig `minHandoffTokens` is set but no token-meter service is composed; mount @deepseek-ai/dsh-token-meter",
    "keepPlanning": "The user chose to keep planning; revise the transition and present it again.",
    "keepPlanningFeedback": "The user chose to keep planning; their feedback: {feedback}",
    "dismissed": "The user dismissed the stage review to speak instead; stay in the current stage, stop here, and wait for their message."
  },
  "command": {
    "description": "Show or switch the current stage",
    "current": "Current stage: {stage}. Stages: {stages}. Use /stage <stage> to switch.",
    "unknown": "Unknown stage \"{target}\". Stages: {stages}.",
    "alreadyCurrent": "Stage {target} is already current.",
    "switched": "Stage switched to {target}.",
    "queued": "Switching to stage {target} (applies from the next step)."
  }
} as const satisfies StageSwitchPrompts
