#!/usr/bin/env node
/**
 * Regenerate `src/prompts.defaults.ts` from `src/prompts.json`.
 *
 * `src/prompts.json` is the single editable source for stage-switch user-facing
 * copy. This script regenerates the embedded fallback (`src/prompts.defaults.ts`)
 * from it — a typed TS module whose default object is the JSON literal itself,
 * so the two stay meaning-identical by construction after every run. The built
 * `lib/` keeps working even when the JSON is absent from a stale install; the
 * tests pin the loaded overlay to this copy so the two cannot drift silently.
 *
 * Run automatically by `npm run build` and `npm test` (via the `prebuild` and
 * `pretest` scripts), so editing `src/prompts.json` and building/testing is all
 * it takes — no manual sync step.
 *
 * @module scripts/sync-prompts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const repoRoot = fileURLToPath(new URL('..', import.meta.url))

/** Absolute path of the single prompt source. */
export function promptsJsonPath(root = repoRoot) {
  return path.join(root, 'src', 'prompts.json')
}

/** Read the prompt source as a plain JS object. */
export function readPrompts(root = repoRoot) {
  return JSON.parse(readFileSync(promptsJsonPath(root), 'utf8'))
}

/**
 * Regenerate `src/prompts.defaults.ts` from `src/prompts.json`. The file is a
 * typed TS module whose default object is the JSON literal itself (a JSON
 * document is valid TypeScript), so the two stay meaning-identical by
 * construction after every sync.
 */
export function writeDefaultsTs(root = repoRoot, prompts = readPrompts(root)) {
  const file = path.join(root, 'src', 'prompts.defaults.ts')
  const json = JSON.stringify(prompts, null, 2)
  const body = `/**
 * Embedded fallback copy of \`src/prompts.json\` plus its type.
 *
 * GENERATED by \`scripts/sync-prompts.mjs\` (run automatically by the
 * \`prebuild\` and \`pretest\` npm scripts) — do not hand-edit the strings
 * here; edit \`src/prompts.json\` instead. The built \`lib/\` keeps working
 * even when the JSON is absent from a stale install (the embedded defaults
 * are the same strings the package always shipped).
 *
 * @module @ai4rpg/dsh-stage-switch/prompts.defaults
 */

/** All user-facing prompt copy owned by stage-switch (formats excluded). */
export interface StageSwitchPrompts {
  /** Model-facing \`goto_stage\` tool copy. */
  readonly gotoTool: {
    readonly description: string
    readonly stageParam: string
    readonly handoffParam: string
  }
  /** The transition-review dialog presented through user-questions. */
  readonly review: {
    readonly header: string
    readonly fullQuestion: string
    readonly lightQuestion: string
    readonly approveLabel: string
    readonly keepStageLabel: string
    readonly fullApproveDescription: string
    readonly lightApproveDescription: string
    readonly keepStageDescription: string
  }
  /** The \`goto_stage\` tool-result render copy. */
  readonly toolResult: {
    readonly approved: string
    readonly handoffPath: string
  }
  /** Tool-call card copy. */
  readonly present: {
    readonly callTitle: string
    readonly lightCallContent: string
    readonly resultTitle: string
  }
  /** Stage-switch notice copy (the \`source.summary\` formats stay in code). */
  readonly notice: {
    readonly handoffReplaced: string
    readonly userSwitchPrefix: string
  }
  /** Failure messages surfaced to the model. */
  readonly errors: Record<
    'notConfigured' | 'alreadyCurrent' | 'requiresHandoff' | 'noUserQuestions'
    | 'noFs' | 'missingTokenMeter' | 'keepPlanning' | 'keepPlanningFeedback' | 'dismissed',
    string
  >
  /** The \`/stage\` command copy. */
  readonly command: {
    readonly description: string
    readonly current: string
    readonly unknown: string
    readonly alreadyCurrent: string
    readonly switched: string
    readonly queued: string
  }
}

/** The fallback copy of \`src/prompts.json\`; regenerated by the sync script. */
export const DEFAULT_STAGE_SWITCH_PROMPTS = ${json} as const satisfies StageSwitchPrompts
`
  writeFileSync(file, body)
  console.log('  ✓ src/prompts.defaults.ts regenerated from src/prompts.json')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeDefaultsTs()
}
